groups:
  - name: Staging Concepts
    role: staging
    notes: >
      Concepts related to staging of neoplastic disease, including TNM and Group stage concepts. These are intended to be used as the entity_concept in staging templates, with permissible values defined in the corresponding value sets.
    registry_members:
      - TStageConcepts
      - NStageConcepts
      - MStageConcepts
      - GroupStageConcepts